### ISSUE TITLE
fix: VectorGroup misspelling

### ISSUE THREAD

**Issue by SebastianDD** [ieeh-tu-dresden/powerfactory-tools#115]

**Comment by sasanjac** [comment]
I'm pretty sure I did it intentionally. If I remember correctly, the value is the PF-internal notation and the name our notation. I'll check and confirm.

**Comment by SebastianDD** [comment]
![0e34f5fc-88c3-47e9-803c-d480751896ef](https://user-images.githubusercontent.com/43751982/233409927-e096f0a1-cde1-428f-85c8-5114ea988d3f.jpg)

Without first letter you could not separate between e.g. DNyn0 and YNyn0.
