### ISSUE TITLE
fix: rated power of LV-loads is average instead of maximum power

### ISSUE THREAD

**Issue by masc622** [ieeh-tu-dresden/powerfactory-tools#145]
In case of LV-loads, the rated power should be the maximum apparent power (cSmax) instead of the average apparent power (cSav). However, an extra information about the average power might be beneficial in some cases.

**Comment by SebastianDD** [comment]
only for flexible part of LV Load:
use cSmax for topology and cSav for steadystate_case

consider to upgrade to PF 2023 (new LV load setup?)
