### ISSUE TITLE
fix: vectorgroup 'YNyn5' is missing

### ISSUE THREAD

**Issue by masc622** [ieeh-tu-dresden/powerfactory-tools#156]
vectorgroup 'YNyn5' is missing in transfomer VectorGroup class

**Comment by SebastianDD** [comment]
fix psdm first [#issue37](https://github.com/ieeh-tu-dresden/power-system-data-model/issues/37)

**Comment by sasanjac** [comment]
is this even possible? 😆

**Comment by masc622** [comment]
technically no, but it is possible to parameterize any vector group in powerfactory. the issue has originally arised from the simbench semiurb MV grid, which uses 110/20kV YNyn5 transformers (why ever).

in my view, a very general question arises therefrom: is it a task of the exporter/data model to restrict vector groups to only technically feasible combinations?

**Comment by sasanjac** [comment]
No, the exporter should be dumb. `psdm` already [supports it](https://github.com/ieeh-tu-dresden/power-system-data-model/pull/43). But maybe we should open an issue [here](https://github.com/e2nIEE/simbench) to investigate why this is used. And maybe also drop a hint to the PF guys to maybe have PF restrict such configurations.

**Comment by masc622** [comment]
seems to be an import issue of simbench grids in powerfactory. even though the vector group is given by YNd5 in the simbench csv files of 1-MV-semiurb--0-no_sw and 1-MV-rural--0-no_sw, the powerfactory transformer has YNyn5

**Comment by masc622** [comment]
> No, the exporter should be dumb. `psdm` already [supports it](https://github.com/ieeh-tu-dresden/power-system-data-model/pull/43). But maybe we should open an issue [here](https://github.com/e2nIEE/simbench) to investigate why this is used. And maybe also drop a hint to the PF guys to maybe have PF restrict such configurations.

in that case psdm must implement any (infeasible) combination of powerfactory vector groups. i suggest to keep only valid vector groups in psdm and to define a default vector group in case that an unknown vector group is parameterized. however, a warning should inform the user

**Comment by SebastianDD** [comment]
> > No, the exporter should be dumb. `psdm` already [supports it](https://github.com/ieeh-tu-dresden/power-system-data-model/pull/43). But maybe we should open an issue [here](https://github.com/e2nIEE/simbench) to investigate why this is used. And maybe also drop a hint to the PF guys to maybe have PF restrict such configurations.
> 
> in that case psdm must implement any (infeasible) combination of powerfactory vector groups. i suggest to keep only valid vector groups in psdm and to define a default vector group in case that an unknown vector group is parameterized. however, a warning should inform the user

I would support this procedure.
In this case we have to revert https://github.com/ieeh-tu-dresden/power-system-data-model/pull/43
