### ISSUE TITLE
fix: transformer data export incomplete

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/powerfactory-tools#158]
I just discovered that the transformer data is not exported right. (Winding 2 r0, r1, x0, x1 missing (?), re and xe missing / null) 
The exported data is:
![grafik](https://github.com/ieeh-tu-dresden/powerfactory-tools/assets/122098671/4c080129-96b8-4aea-b420-270a907ba3e2)
There are no values for  r0, r1, x0, x1 for winding 2 or are they specified for the whole transformer (which would be more plausible to me), if so, why are they stored under windings and not with p_fe and i_0 directly under transformer
![grafik](https://github.com/ieeh-tu-dresden/powerfactory-tools/assets/122098671/2fc00043-e9db-4a9b-95ff-8755d2b465f9)
In addition re and xe are missing 
![grafik](https://github.com/ieeh-tu-dresden/powerfactory-tools/assets/122098671/70419a32-cced-4552-b179-0c1bc33edd39)

**Comment by sasanjac** [comment]
As far as I know, the whole transformer export is incorrect and needs rework by @FiedLa :)

**Comment by sasanjac** [comment]
Also export zero sequence magnetization data
