### ISSUE TITLE
fix: activate only grids to be exported

### ISSUE THREAD

**Issue by SebastianDD** [ieeh-tu-dresden/powerfactory-tools#160]
check if only the grid to be exported is activated.

otherwise there could be problems when applying scenarios etc

should be solved together with #136

**Comment by sasanjac** [comment]
Do you mean the other way around, e.g. check if only the activated grid is exported? Can you activate more than one grid in PF?

**Comment by SebastianDD** [comment]
No, I mean we specify the grid_name of the grid to be exported. For this simple case it does not matter if active or not. But if we apply operation cases or if we not prelude that a operation case is currently active, then we have to care about that the grid to be exported is active.

Yes, it is possible that more than one grid is active.
