### ISSUE TITLE
feat: topology case meta information

### ISSUE THREAD

**Issue by SebastianDD** [ieeh-tu-dresden/powerfactory-tools#164]
add the case name to the meta data of topology case and steadstate case.

first fix https://github.com/ieeh-tu-dresden/power-system-data-model/issues/39 

But, not sure which information we should store in meta data case name:
* operation set
* grid variant

**Comment by sasanjac** [comment]
We have to create a clean workflow structure with which this tools is intended to be used. Then we can define the necessary information which describes a case.
