### ISSUE TITLE
feat: mapping back the system_type to type for loads

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/powerfactory-tools#168]
i have noticed, that for an ElmGenstat with the system_type (Anlagenkategorie) battery storage the type is still "PRODUCER". is this intentional? i think it would be better to map the attribute system_type back to the attribute type, so that for this load the type is changed to "STORAGE". Or which element does produce the type "STORAGE" in the first place? :-)
![grafik](https://github.com/ieeh-tu-dresden/powerfactory-tools/assets/122098671/cb8b165d-22df-4c53-bf2a-df09edd27dd0)

maybe another a bit off-topic question: what is an use case for the attribute voltage system type. the battery is connected to an AC system nevertheless the voltage system type is DC (same for PV). is this an internal attribute of power factory?

**Comment by SebastianDD** [comment]
1) confirm -> new approach: consdider a `ElmGenstat ` with system_type "xx_Storage" as an `Load `from type "STORAGE"

2) meanwhile, the second question is obsolete.  `ElmGenstat `from system_type "Battery" or "PV" have the voltage system type AC. Only a real Batttery `ElmBattery` has the voltage system type DC.
