### ISSUE TITLE
fix: study_case_dir error when using function call of exporter

### ISSUE THREAD

**Issue by masc622** [ieeh-tu-dresden/powerfactory-tools#280]
following error occurs when trying to export via function call `export_powerfactory_data()` 
     
`AttributeError: 'PowerFactoryInterface' object has no attribute 'study_case_dir'`

however, exporting using exporter as an instance works well

tested versions:
ieeh-power-system-data-model 2.3.1
ieeh-powerfactory-tools      3.0.1

**Comment by SebastianDD** [comment]
solved with PR #279
