### ISSUE TITLE
feat: change data model loads rated power values cos phi to array 

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/powerfactory-tools#80]

**Comment by SebastianDD** [comment]
As rated reactive power can be asymmetrical (e.g. Consumer Load would only be ohmic-inductive), we propose to extend the reated cosphi values and specify value for the under-excited (ue) and over-excited (oe) operation. 
So cosphi would be an array [cosphi_ue, cosphi_oe]

**Comment by SebastianDD** [comment]
Agreement:
* rename phase identifier from r,s,t to a,b,c
* add 4 more entries for rated power cosphi --> cosphi_ue, cosphi_oe
* cosphi default should be 1
