### ISSUE TITLE
feat: add connection phase to phase_connection_type in case of 1ph or 2ph connected loads/generators

### ISSUE THREAD

**Issue by masc622** [ieeh-tu-dresden/powerfactory-tools#81]
currently the powerfactory phase technology string is exported via phase_connection_type, e.g. "3PH_D" or "1PH_PH_E"
however, the information about the connected phase is missing.
suggestion: add phase information separated by ":" to phase_connection_type in case of "1PH" and "2PH" connected loads/generator. example: "1PH_PH_E:A" for a single phase connection to phase "A" and "2PH_Y_N:BC" for double phase connection to phases "B" and "C"

**Comment by SebastianDD** [comment]
same issue appears for single-phase transformers!

**Comment by sasanjac** [comment]
1. I'd prefer a list of phases instead of some string code, e.g. ["A", "B", "C"]. This way, we can validate everything without too much complexity
2. Should we include neutral as a valid phase?

**Comment by FiedLa** [comment]
I discussed with @SebastianDD, that the phase connection type SPN /SP-E is not in the scope of the project, this should be documented
