### ISSUE TITLE
feat: adapt s_rst to phase connection type of loads 

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/powerfactory-tools#86]
in case of SYMMETRICAL single phase/ two phase loads: power is calculated assuming a 3phase load. 
the information saved in `phase_connection_type ` and `connected_phases` is not feedbacked to the apparent power (topology) as well as active resp. reactive power (steady state).
Example: Symmetrical 1PH PH-E with s=10 MW --> `s_a = s_b = s_c = s/3.`  

Additonally: Proposed nomenclature if load is connected between 2 phases `1PH PH-PH` analogous to 3PH loads from type D:
* between L1 und L2: --> assigned to phase a
* between L2 und L3: --> assigned to phase b
* between L1 und L3: --> assigned to phase c

**Comment by sasanjac** [comment]
> in case of SYMMETRICAL single phase/ two phase loads: power is calculated assuming a 3phase load. the information saved in `phase_connection_type ` and `connected_phases` is not feedbacked to the apparent power (topology) as well as active resp. reactive power (steady state). Example: Symmetrical 1PH PH-E with s=10 MW --> `s_a = s_b = s_c = s/3.`

This is a tricky one because from the `Power` objects POV it is an asymmetric load since by default all loads are three-phase loads. I think we'd have to change this first. Like specifying how many phases the load is connected to and then keeping the phase loads as vector instead of attributes.

**Comment by sasanjac** [comment]
> Additonally: Proposed nomenclature if load is connected between 2 phases `1PH PH-PH` analogous to 3PH loads from type D:
> 
> * between L1 und L2: --> assigned to phase a
> * between L2 und L3: --> assigned to phase b
> * between L1 und L3: --> assigned to phase c

What does "assigned" here mean? It should have two elements in `connected_phases`.

**Comment by SebastianDD** [comment]
first resolve https://github.com/ieeh-tu-dresden/power-system-data-model/issues/21

Additional, loads that are not 3phase has to be stated as asymmetrical in the exporter.
