### ISSUE TITLE
fix: calculation rated power for low voltage loads

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/powerfactory-tools#88]
load is defined by current and cosphi
![grafik](https://user-images.githubusercontent.com/122098671/220637850-a448c7bf-fd5d-4c60-bc42-a8fe5734e158.png)

rated power ist calculated by exporter with ULL*I, but this ist not right. instead it should be ULL/sqrt(3)*I*3 !

**Comment by sasanjac** [comment]
Good catch, but why divide by 3? The exporter calculates three-phase power.

**Comment by FiedLa** [comment]
> Good catch, but why divide by 3? The exporter calculates three-phase power.

That is true. GitHub did something weird with my equation: 
![grafik](https://user-images.githubusercontent.com/122098671/220655337-d7489e46-f289-421d-8551-b3c783f1b6d6.png)
of course it is ULL/ sqrt(3) * current * 3
